import './globals.css'
import { Roboto } from 'next/font/google'
import NavMenu from "@/app/NavMenu";
import AuthProvider from '@/app/AuthProvider';

const inter = Roboto({ weight: ['400', '500', '700', '900'], subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <NavMenu />
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
